user_notification:
    channel: notification/user/{role}/{application}/{user_ref}
    handler: ['App\Chat\MessageHandler', 'notifyUser']
    requirements:
        role: 'editor|admin|client'
        user_ref: '\d+'
